<?php
return [
    'shop_categories_blueprint' => [
        'apparel' => [
            'title' => 'Apparel & Garments',
            'description' => 'High-end minimalist garments crafted from sustainable fine cashmere and merino.',
            'image_file' => 'graphene-thermal-shirt.jpg',
        ],
        'utility' => [
            'title' => 'Studio Utility',
            'description' => 'Minimalist hardware, desk organizers, and fine writing instruments for modern creative spaces.',
            'image_file' => 'laser-utility-belt.jpg',
        ],
        'vessels' => [
            'title' => 'Minimalist Vessels',
            'description' => 'Sculpted stoneware, hand-blown glass vessels, and copper-accented burners.',
            'image_file' => 'neural-interface-core.jpg',
        ],
    ],
    'shop_products_blueprint' => [
        [
            'category' => 'apparel',
            'title' => 'Obsidian Cashmere Trench Coat',
            'slug' => 'obsidian-cashmere-trench-coat',
            'sku' => 'LUXE-AP-01',
            'description' => '<p>The Obsidian Cashmere Trench Coat is a masterclass in minimalist structural utility. Handcrafted using premium, sustainably sourced Cashmere, this Trench Coat embodies the raw tactile essence of modern brutalist design.</p>',
            'price' => 285.0,
            'compare_price' => 350.0,
            'image_file' => 'graphene-thermal-shirt.jpg',
            'variants' => [
                [
                    'title' => 'Obsidian Black / Small',
                    'sku' => 'LUXE-AP-01-S',
                    'price' => 285.0,
                    'stock' => 12,
                ],
                [
                    'title' => 'Obsidian Black / Medium',
                    'sku' => 'LUXE-AP-01-M',
                    'price' => 285.0,
                    'stock' => 15,
                ],
                [
                    'title' => 'Obsidian Black / Large',
                    'sku' => 'LUXE-AP-01-L',
                    'price' => 285.0,
                    'stock' => 8,
                ],
            ],
        ],
        [
            'category' => 'apparel',
            'title' => 'Graphene Thermal Shirt',
            'slug' => 'graphene-thermal-shirt',
            'sku' => 'LUXE-AP-02',
            'description' => '<p>Engineered for perfect thermoregulation, the Graphene Thermal Shirt integrates lightweight Graphene fibers into premium merino wool threads.</p>',
            'price' => 85.0,
            'compare_price' => null,
            'image_file' => 'graphene-thermal-shirt.jpg',
            'variants' => [
                [
                    'title' => 'Slate Grey / Small',
                    'sku' => 'LUXE-AP-02-S',
                    'price' => 85.0,
                    'stock' => 20,
                ],
                [
                    'title' => 'Slate Grey / Medium',
                    'sku' => 'LUXE-AP-02-M',
                    'price' => 85.0,
                    'stock' => 25,
                ],
                [
                    'title' => 'Slate Grey / Large',
                    'sku' => 'LUXE-AP-02-L',
                    'price' => 85.0,
                    'stock' => 18,
                ],
            ],
        ],
        [
            'category' => 'apparel',
            'title' => 'Carbon Exoskeleton Arm',
            'slug' => 'carbon-exoskeleton-arm',
            'sku' => 'LUXE-AP-03',
            'description' => '<p>A masterpiece of lightweight carbon composites. The Carbon Exoskeleton Arm attaches to premium utility jackets to provide active mechanical lifting assistance.</p>',
            'price' => 1200.0,
            'compare_price' => 1400.0,
            'image_file' => 'carbon-exoskeleton-arm.jpg',
            'variants' => [
                [
                    'title' => 'Standard Carbon Weave',
                    'sku' => 'LUXE-AP-03-STD',
                    'price' => 1200.0,
                    'stock' => 3,
                ],
                [
                    'title' => 'Reinforced Matte Edition',
                    'sku' => 'LUXE-AP-03-REIN',
                    'price' => 1350.0,
                    'stock' => 2,
                ],
            ],
        ],
        [
            'category' => 'apparel',
            'title' => 'Neon Cyan Cyber Gloves',
            'slug' => 'neon-cyan-cyber-gloves',
            'sku' => 'LUXE-AP-04',
            'description' => '<p>High-contrast, high-visibility tactile gloves featuring conductive fingertips and smart HUD synchronization.</p>',
            'price' => 45.0,
            'compare_price' => null,
            'image_file' => 'neon-cyan-cyber-gloves.jpg',
            'variants' => [
                [
                    'title' => 'Neon Cyan / Medium',
                    'sku' => 'LUXE-AP-04-M',
                    'price' => 45.0,
                    'stock' => 30,
                ],
                [
                    'title' => 'Neon Cyan / Large',
                    'sku' => 'LUXE-AP-04-L',
                    'price' => 45.0,
                    'stock' => 22,
                ],
            ],
        ],
        [
            'category' => 'apparel',
            'title' => 'Cyberware Boot Liners',
            'slug' => 'cyberware-boot-liners',
            'sku' => 'LUXE-AP-05',
            'description' => '<p>Premium padded interior boot liners engineered for rugged all-terrain exploration and shock mitigation.</p>',
            'price' => 110.0,
            'compare_price' => 130.0,
            'image_file' => 'cyberware-boot-liners.jpg',
            'variants' => [
                [
                    'title' => 'Universal Size / Pair',
                    'sku' => 'LUXE-AP-05-UNIV',
                    'price' => 110.0,
                    'stock' => 40,
                ],
            ],
        ],
        [
            'category' => 'apparel',
            'title' => 'Glow Cyber Vest',
            'slug' => 'glow-cyber-vest',
            'sku' => 'LUXE-AP-06',
            'description' => '<p>Luminous electroluminescent cybernetic vest. Weatherproof and fully programmable, it delivers state-of-the-art night visibility.</p>',
            'price' => 195.0,
            'compare_price' => 225.0,
            'image_file' => 'glow-cyber-vest.jpg',
            'variants' => [
                [
                    'title' => 'Standard Glow / Black',
                    'sku' => 'LUXE-AP-06-STD',
                    'price' => 195.0,
                    'stock' => 10,
                ],
                [
                    'title' => 'Tactical Armor Edition',
                    'sku' => 'LUXE-AP-06-TACT',
                    'price' => 250.0,
                    'stock' => 5,
                ],
            ],
        ],
        [
            'category' => 'utility',
            'title' => 'Matte Titanium Writing Instrument',
            'slug' => 'matte-titanium-writing-instrument',
            'sku' => 'LUXE-UT-01',
            'description' => '<p>An exceptional titanium mechanical pen featuring seamless knurled grip, weighted balancing, and custom-etched brand signatures.</p>',
            'price' => 125.0,
            'compare_price' => null,
            'image_file' => 'laser-utility-belt.jpg',
            'variants' => [
                [
                    'title' => 'Matte Titanium Silver',
                    'sku' => 'LUXE-UT-01-SIL',
                    'price' => 125.0,
                    'stock' => 15,
                ],
                [
                    'title' => 'Stealth Anodized Black',
                    'sku' => 'LUXE-UT-01-BLK',
                    'price' => 135.0,
                    'stock' => 10,
                ],
            ],
        ],
        [
            'category' => 'utility',
            'title' => 'Laser Utility Belt',
            'slug' => 'laser-utility-belt',
            'sku' => 'LUXE-UT-02',
            'description' => '<p>Brutalist structural utility belt featuring active laser levelers, cryptographic hardware slots, and magnetized component mounts.</p>',
            'price' => 150.0,
            'compare_price' => 180.0,
            'image_file' => 'laser-utility-belt.jpg',
            'variants' => [
                [
                    'title' => 'Tactical Nylon Black',
                    'sku' => 'LUXE-UT-02-NYL',
                    'price' => 150.0,
                    'stock' => 12,
                ],
            ],
        ],
        [
            'category' => 'utility',
            'title' => 'Solid Neuro Drive',
            'slug' => 'solid-neuro-drive',
            'sku' => 'LUXE-UT-03',
            'description' => '<p>A hyper-speed solid-state neural database storage drive. Integrates hardware-level encryption and full biometrics check blocks.</p>',
            'price' => 95.0,
            'compare_price' => null,
            'image_file' => 'solid-neuro-drive.jpg',
            'variants' => [
                [
                    'title' => '1TB Ultra-Speed',
                    'sku' => 'LUXE-UT-03-1TB',
                    'price' => 95.0,
                    'stock' => 20,
                ],
                [
                    'title' => '2TB Hyper-Speed',
                    'sku' => 'LUXE-UT-03-2TB',
                    'price' => 165.0,
                    'stock' => 15,
                ],
            ],
        ],
        [
            'category' => 'utility',
            'title' => 'Bio-Link Wrist Strap',
            'slug' => 'bio-link-wrist-strap',
            'sku' => 'LUXE-UT-04',
            'description' => '<p>Active biological feedback strap. Measures nervous network bandwidth, cardiovascular states, and system stress telemetry.</p>',
            'price' => 35.0,
            'compare_price' => 45.0,
            'image_file' => 'bio-link-wrist-strap.jpg',
            'variants' => [
                [
                    'title' => 'Bio-Link / Cyber-Green',
                    'sku' => 'LUXE-UT-04-GRN',
                    'price' => 35.0,
                    'stock' => 50,
                ],
                [
                    'title' => 'Bio-Link / Stealth-Black',
                    'sku' => 'LUXE-UT-04-BLK',
                    'price' => 35.0,
                    'stock' => 45,
                ],
            ],
        ],
        [
            'category' => 'utility',
            'title' => 'Cyberware Optics HUD Glasses',
            'slug' => 'cyberware-optics-hud-glasses',
            'sku' => 'LUXE-UT-05',
            'description' => '<p>Sleek, lightweight smart spectacles carrying high-contrast HUD optics, threat analysis telemetry, and live coding highlighting.</p>',
            'price' => 220.0,
            'compare_price' => 250.0,
            'image_file' => 'cyberware-optics-hud-glasses.jpg',
            'variants' => [
                [
                    'title' => 'Polarized Clear HUD',
                    'sku' => 'LUXE-UT-05-CLR',
                    'price' => 220.0,
                    'stock' => 15,
                ],
                [
                    'title' => 'Chameleon Solar Shade',
                    'sku' => 'LUXE-UT-05-SHD',
                    'price' => 240.0,
                    'stock' => 12,
                ],
            ],
        ],
        [
            'category' => 'utility',
            'title' => 'Nanite Maintenance Pack',
            'slug' => 'nanite-maintenance-pack',
            'sku' => 'LUXE-UT-06',
            'description' => '<p>Advanced software and physical diagnostics kit carrying raw neural probes and micro-fuses for real-time cybernetic repair.</p>',
            'price' => 75.0,
            'compare_price' => null,
            'image_file' => 'nanite-maintenance-pack.jpg',
            'variants' => [
                [
                    'title' => 'Standard Diagnostics Pack',
                    'sku' => 'LUXE-UT-06-STD',
                    'price' => 75.0,
                    'stock' => 25,
                ],
            ],
        ],
        [
            'category' => 'vessels',
            'title' => 'Solid Stoneware Clay Burner',
            'slug' => 'solid-stoneware-clay-burner',
            'sku' => 'LUXE-VS-01',
            'description' => '<p>A brutalist, sculpted stoneware container handcrafted to burn active natural clays, fine resins, and incense. Retains heat for outstanding diffusion.</p>',
            'price' => 115.0,
            'compare_price' => null,
            'image_file' => 'neural-interface-core.jpg',
            'variants' => [
                [
                    'title' => 'Clay Burner / Terracotta',
                    'sku' => 'LUXE-VS-01-TERR',
                    'price' => 115.0,
                    'stock' => 18,
                ],
                [
                    'title' => 'Clay Burner / Slate Grey',
                    'sku' => 'LUXE-VS-01-SLATE',
                    'price' => 115.0,
                    'stock' => 14,
                ],
            ],
        ],
        [
            'category' => 'vessels',
            'title' => 'Holographic Projector Disk',
            'slug' => 'holographic-projector-disk',
            'sku' => 'LUXE-VS-02',
            'description' => '<p>A dynamic hand-blown glass vessel that doubles as a high-contrast holographic refraction platform for ambient spatial lighting.</p>',
            'price' => 350.0,
            'compare_price' => 400.0,
            'image_file' => 'holographic-projector-disk.jpg',
            'variants' => [
                [
                    'title' => 'Atmospheric Refraction Disk',
                    'sku' => 'LUXE-VS-02-REF',
                    'price' => 350.0,
                    'stock' => 8,
                ],
            ],
        ],
        [
            'category' => 'vessels',
            'title' => 'Quantum Deck Console',
            'slug' => 'quantum-deck-console',
            'sku' => 'LUXE-VS-03',
            'description' => '<p>Premium computing terminal chassis sculpted from a solid block of aluminum. Houses active liquid cooling channels and modular board nodes.</p>',
            'price' => 850.0,
            'compare_price' => 950.0,
            'image_file' => 'quantum-deck-console.jpg',
            'variants' => [
                [
                    'title' => '64 Core / Standard',
                    'sku' => 'LUXE-VS-03-64',
                    'price' => 850.0,
                    'stock' => 5,
                ],
                [
                    'title' => '128 Core Pro Edition',
                    'sku' => 'LUXE-VS-03-128',
                    'price' => 1150.0,
                    'stock' => 3,
                ],
            ],
        ],
        [
            'category' => 'vessels',
            'title' => 'Neural Interface Core',
            'slug' => 'neural-interface-core',
            'sku' => 'LUXE-VS-04',
            'description' => '<p>A dynamic mechanical sculpture that monitors localized Wi-Fi grids and compiles active visual telemetry inside a stunning fluid sphere.</p>',
            'price' => 650.0,
            'compare_price' => null,
            'image_file' => 'neural-interface-core.jpg',
            'variants' => [
                [
                    'title' => 'Telemetry Core / Matte Black',
                    'sku' => 'LUXE-VS-04-BLK',
                    'price' => 650.0,
                    'stock' => 7,
                ],
            ],
        ],
        [
            'category' => 'vessels',
            'title' => 'Cryo-Cooler Module',
            'slug' => 'cryo-cooler-module',
            'sku' => 'LUXE-VS-05',
            'description' => '<p>Advanced active cooling block styled after modern spacecraft manifolds. Ensures pristine computing speeds during heavy recursive compilations.</p>',
            'price' => 180.0,
            'compare_price' => 210.0,
            'image_file' => 'cryo-cooler-module.jpg',
            'variants' => [
                [
                    'title' => 'Cryo-Cooler Standard Pack',
                    'sku' => 'LUXE-VS-05-STD',
                    'price' => 180.0,
                    'stock' => 15,
                ],
            ],
        ],
    ],
];
