<?php

namespace Zero\Services\Ai\Providers;

use Zero\Interfaces\AiProvider;
use Exception;

class MockProvider implements AiProvider
{
    /**
     * Generate standard mock content.
     *
     * @param string $prompt The prompt string.
     * @param array $options Optional configuration parameters.
     * @return string Generated content.
     * @throws Exception
     */
    public function generate(string $prompt, array $options = []): string
    {
        if (isset($options['should_fail']) && $options['should_fail']) {
            throw new Exception("Simulated AI Provider Failure.");
        }
        return $options['mock_response'] ?? "## MOCK AI RESPONSE\n\nThis is a mock AI response generated by the offline MockProvider. Prompt received: " . substr($prompt, 0, 50) . "...";
    }
}
