<?php
/**
 * File: src/Services/Ai/Providers/MockProvider.php
 * Architectural Purpose: Handles operations and business logic within the system.
 * Package: Zero\Services\Ai\Providers
 * Systemic Role: Standardized, zero-dependency engine component supporting secure platform execution.
 */

namespace Zero\Services\Ai\Providers;

use Zero\Interfaces\AiProvider;
use Exception;
use Zero\Support\Str;

/**
 * Class MockProvider
 *
 * Provides structural platform implementation and operational encapsulation.
 */
class MockProvider implements AiProvider
{
    /**
     * Generate standard mock content.
     *
     * @param string $prompt The prompt string.
     * @param array $options Optional configuration parameters.
     * @return string Generated content.
     * @throws Exception
     */
    public function generate(string $prompt, array $options = []): string
    {
        if (isset($options['should_fail']) && $options['should_fail']) {
            throw new Exception("Simulated AI Provider Failure.");
        }
        return $options['mock_response'] ?? "## MOCK AI RESPONSE\n\nThis is a mock AI response generated by the offline MockProvider. Prompt received: " . substr($prompt, 0, 50) . "...";
    }

    /**
     * Generate a mock SVG image vector encoded as Base64.
     *
     * @param string $prompt The prompt string.
     * @param array $options Optional configuration parameters.
     * @return string Generated image Base64 string.
     * @throws Exception
     */
    public function generateImage(string $prompt, array $options = []): string
    {
        if (isset($options['should_fail']) && $options['should_fail']) {
            throw new Exception("Simulated AI Image Provider Failure.");
        }
        $svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" fill="#0b0f19"/><text x="10" y="50" fill="#00f0ff">Mock Image: ' . Str::escape($prompt) . '</text></svg>';
        return base64_encode($svg);
    }
}
